# Generated by Django 3.2.5 on 2021-08-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
